
services:
  mysql:
    image: mysql:5.7
    container_name: mysql_hotel
    environment:
      MYSQL_ROOT_PASSWORD: Admin-123
      MYSQL_DATABASE: bd_hotel
      MYSQL_USER: root
      MYSQL_PASSWORD: Admin-123
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    networks:
      - hotel_net

  haproxy:
    image: haproxy:2.7
    container_name: haproxy
    ports:
      - "80:80"
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    depends_on:
      - mysql
    networks:
      - hotel_net

networks:
  hotel_net:
    driver: bridge



